/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author deepika
 */
package cms;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class rol extends javax.swing.JFrame {

    /**
     * Creates new form rol
     */
    public rol() {
        initComponents();
        setSize(555,434);
        setLocation(300,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        passcode1 = new javax.swing.JTextField();
        passcode2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(555, 434));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/deepika/Pictures/font.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 40, 180, 40);

        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(380, 330, 90, 29);

        login.setText("SIGN IN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(380, 130, 80, 29);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 180, 90, 17);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 230, 68, 17);

        jLabel5.setText("Re-type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 280, 80, 17);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(410, 180, 130, 27);

        passcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passcode1ActionPerformed(evt);
            }
        });
        getContentPane().add(passcode1);
        passcode1.setBounds(410, 220, 130, 27);

        passcode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passcode2ActionPerformed(evt);
            }
        });
        getContentPane().add(passcode2);
        passcode2.setBounds(410, 270, 130, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/rol1.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1, 0, 580, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String u = new String(user.getText());
        String p = new String(passcode1.getText());
        String p2 = new String(passcode2.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = (Connection) 
             DriverManager.getConnection("jdbc:mysql://localhost:3306/cms","root","");
             String query = "select password from user_details where username = '"+u+"';";
             String q = "insert into user_details (username,password) values('"+u+"','"+p+"');";
             Statement stmt = (Statement) con.createStatement();
             ResultSet rs = stmt.executeQuery(query);
            if (rs.next())
            {
                JOptionPane.showMessageDialog(null,"ACCOUNT EXISTS;(");
                this.setVisible(false);
                new login().setVisible(true);
            }
            else
            {
                if(p2.equals(p))
                {
                    stmt.executeUpdate(q);
                    JOptionPane.showMessageDialog(null,"ACCOUNT CREATED SUCCESSFULLY ;)");
                    this.setVisible(false);
                    new login().setVisible(true);
                }
                else
                {
                   JOptionPane.showMessageDialog(null,"PASSWORDS DON'T MATCH;(");
                   this.setVisible(true);

                }
                
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_registerActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
                   user.getText();                   
    }//GEN-LAST:event_userActionPerformed

    private void passcode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passcode2ActionPerformed
        // TODO add your handling code here:
        passcode2.getText();
    }//GEN-LAST:event_passcode2ActionPerformed

    private void passcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passcode1ActionPerformed
        // TODO add your handling code here:
        passcode1.getText();
    }//GEN-LAST:event_passcode1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton login;
    private javax.swing.JTextField passcode1;
    private javax.swing.JTextField passcode2;
    private javax.swing.JButton register;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
